In [26]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('HeartDiseaseTrain-Test.csv')
data.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [30]:
# This converts 'Sex' with "Male/Female" into a column of 1s and 0s
data = pd.get_dummies(df, drop_first=True)

In [31]:
X = data.drop(columns = ['target'])
y = data['target']

In [32]:
X

,age,resting_blood_pressure,cholestoral,Max_heart_rate,oldpeak,sex_Male,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,fasting_blood_sugar_Lower than 120 mg/ml,...,exercise_induced_angina_Yes,slope_Flat,slope_Upsloping,vessels_colored_by_flourosopy_One,vessels_colored_by_flourosopy_Three,vessels_colored_by_flourosopy_Two,vessels_colored_by_flourosopy_Zero,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,52,125,212,168,1.0,True,False,False,True,True,...,False,False,False,False,False,True,False,False,False,True
1,53,140,203,155,3.1,True,False,False,True,False,...,True,False,True,False,False,False,True,False,False,True
2,70,145,174,125,2.6,True,False,False,True,True,...,True,False,True,False,False,False,True,False,False,True
3,61,148,203,161,0.0,True,False,False,True,True,...,False,False,False,True,False,False,False,False,False,True
4,62,138,294,106,1.9,False,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,140,221,164,0.0,True,True,False,False,True,...,True,False,False,False,False,False,True,False,False,False
1021,60,125,258,141,2.8,True,False,False,True,True,...,True,True,False,True,False,False,False,False,False,True
1022,47,110,275,118,1.0,True,False,False,True,True,...,True,True,False,True,False,False,False,False,False,False
1023,50,110,254,159,0.0,False,False,False,True,True,...,False,False,False,False,False,False,True,False,False,False
1024,54,120,188,113,1.4,True,False,False,True,True,...,False,True,False,True,False,False,False,False,False,True

In [33]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [115]:
# Model
model = KNeighborsClassifier(n_neighbors = 3, metric = 'manhattan')

In [116]:
# Train the model
model.fit(X_train, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=3)

In [117]:
#Predictions
y_pred = model.predict(X_test)

In [118]:
print(y_pred)

[0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1
 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1
 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1
 0 1 1 1 0 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1
 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 0 1 1 0 1 1 0
 1 1 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 1 1]

In [119]:
#Check performance
print('Accuracy:', accuracy_score(y_pred, y_test))
print('CM\n', confusion_matrix(y_pred, y_test))

Accuracy: 0.8585365853658536
CM
 [[86 15]
 [14 90]]

In [120]:
X_test.shape

(205, 22)

In [121]:
scaler = StandardScaler()

In [122]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [123]:
model.fit(X_train_scaled, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=3)

In [124]:
y_pred_scaled = model.predict(X_test_scaled)

In [125]:
print('Accuracy', accuracy_score(y_pred_scaled, y_test))
print('CM\n', confusion_matrix(y_pred_scaled, y_test))

Accuracy 0.9365853658536586
CM
 [[95  8]
 [ 5 97]]

In [126]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline

In [ ]:
# 1. Create a Pipeline: This ensures scaling happens INSIDE each cross-validation fold
knn_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier(n_neighbors=3, metric='manhattan'))
])

In [128]:
cv_strategy= StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(knn_pipeline, X, y, cv=cv_strategy)

In [129]:
print(f"accuracy per fold: {cv_scores}")
print(f"average accuracy: {cv_scores.mean():.4f}")
print(f"Standard Deviation: {cv_scores.std():.4f}")

accuracy per fold: [0.94634146 0.95609756 0.9804878  0.97560976 0.94634146]
average accuracy: 0.9610
Standard Deviation: 0.0145